### ISSUE TITLE
cannot set root to run CheckM

### ISSUE THREAD

**Issue by nixon444** [Ecogenomics/CheckM#163]
Hi,

I am trying to run CheckM on my mac after installing it through miniconda. I have used CheckM before without problems (on a VM) but I am stuck at setting the root and keep getting the following error messages:

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /xxxx/xxxx/miniconda3/lib/python2.7/site-packages/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 13] Permission denied: '/xxxx/xxxx/miniconda3/lib/python2.7/site-packages/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.

I have tried specifying a different absolute path and that doesn't work. What am I doing wrong here? How can I fix this?

Cheers!

**Comment by dparks1134** [comment]
Hello. It looks like you either need to install CheckM to your home directory or run the "checkm data setRoot' command as sudo. If CheckM has been installed system wide, your sys admin should configure the CheckM data directory for you and all other users.

**Comment by nixon444** [comment]
Thanks, that solved one problem and I was able to run successfully until I hit this error:

[Error] Make sure pplacer is on your system path

Do I need to move pplacer to the folder I am writing to each time I run it? (I realise I could try this but it would be good to know for future reference...)

**Comment by dparks1134** [comment]
Just needs to be on your system path:
https://www.computerhope.com/issues/ch001647.htm

**Comment by nixon444** [comment]
Ah ok, thanks very much! And thanks for such quick responses. Loving the tool by the way.

**Comment by nixon444** [comment]
OK I spoke too soon. I have now added pplacer to my system path and it still is not working:

  [Error] Make sure pplacer is on your system path.

  Controlled exit resulting from an unrecoverable error or warning.

Any ideas??

**Comment by dparks1134** [comment]
If you type "pplacer" on the command line does pplacer run? If not, then it isn't properly on the system path. You might check that the executable is actually called pplacer on your system.

**Comment by nixon444** [comment]
When I type in "pplacer" I get this:

-bash: /xxxx/xxxx/miniconda3/bin/pplacer: cannot execute binary file

So that means it's not properly installed then?

**Comment by dparks1134** [comment]
Seems that way.

**Comment by nixon444** [comment]
OK thanks, will uninstall/reinstall a different way, hopefully that sorts it. Probably obvious but I'm a relative newby to bioinformatics!

**Comment by maymystery** [comment]
Hi, I met the same problem.
Through checking, pplacer is already on my system path.
Run it individually. it shows:
:~$ pplacer
Warning: pplacer couldn't find any sequences to place. Please supply an alignment with sequences to place as an argument at the end of the command line.

Then I use 'echo $PATH', obviously pplacer is on the system path, the last one:
/home/.....:/usr/local/games:/snap/bin:/home/yuke/pplacer-Linux-v1.1.alpha19

And then I run checkm, it still shows:
....  [Error] Make sure pplacer is on your system path.
  Controlled exit resulting from an unrecoverable error or warning.

After do that, it already completed some genomes data with checkm, no errors.

Any ideas??

**Comment by dparks1134** [comment]
Did you manage to solve this issue?

**Comment by nixon444** [comment]
I never managed to solve this problem :(

I have now tried this locally on my Mac and on a couple of different VMs. I didn't run in to this issue when I first tried using CheckM in May, but every time I have tried since (using more recent versions?) I have run into this problem and never achieve the summary table print out I got on successful runs. Could it be an installation issue with a more recent version? Any way of trying an older version?

**Comment by nixon444** [comment]
FYI I ran pplacer on teh command line and got: 

Warning: pplacer couldn't find any sequences to place. Please supply an alignment with sequences to place as an argument at the end of the command line.

So it seems that pplacer has been installed crrectly this time, unlike before. I also added it to my system path already...

**Comment by nixon444** [comment]
This is the error I get now:

$ checkm lineage_wf -x fasta /home/ubuntu/greenland_data/maxbin_idba /home/ubuntu/greenland_data/maxbin_idba/checkm

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 10 bins with 1 threads:
Process Process-2:ssing 0 of 10 (0.00%) bins.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/ubuntu/checkm/hmms/phylo.hmm'

  Saving HMM info to file.

  Calculating genome statistics for 10 bins with 1 threads:
    Finished processing 10 of 10 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/bin/checkm", line 709, in <module>
    checkmParser.parseOptions(args)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1253, in parseOptions
    self.tree(options)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 104, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1213, in parseOptions
    if options.bVerbose:
AttributeError: 'Namespace' object has no attribute 'bVerbose'

Is this a problem through installing with conda?

**Comment by dparks1134** [comment]
The 'bVerbose' issue should be addressed in CheckM v1.0.12. The other errors suggest and issue with HMMER. Can you verify that hmmsearch is on your path and that it is version >=3.1b1?

**Comment by nixon444** [comment]
Conda installed the previous version of CheckM so I'll switch to the latest - is v1.0.12 available through pip?

**Comment by nixon444** [comment]
OK I now have the latest version of checkm via pip, having uninstalled the previous version I got using conda (using the conda uninstall command). I still get pretty much the same error regarding the whereabouts of phylo.hmm - how do I locate this so I can copy elsewhere? It is looking for it in the folder I pointed to when promptem SetRoot, maybe this was a mistake - is there a more logical root to set?

Output of running 'checkm lineage_wf' with v1.0.12:

checkm lineage_wf -x fasta /home/ubuntu/greenland_data/maxbin_idba /home/ubuntu/greenland_data/maxbin_idba/checkm

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 10 bins with 1 threads:
Process Process-2:ssing 0 of 10 (0.00%) bins.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/ubuntu/checkmdata/hmms/phylo.hmm'

  Saving HMM info to file.

  Calculating genome statistics for 10 bins with 1 threads:
    Finished processing 10 of 10 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 105, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/checkm/resultsParser.py", line 85, in parseBinHits
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

**Comment by dparks1134** [comment]
Hello. Does the file /home/ubuntu/checkmdata/hmms/phylo.hmm exist? This is part of the dependency data required by CheckM. The path is set with `checkm data setRoot`.

**Comment by nixon444** [comment]
The file isn't in that path, but I don't know how to find it or figure out if I even have it...

Also I notice that checkm is still looking for dependencies in the conda-installed version, which I uninstalled. But when I type 'whereis checkm' I get /home/ubuntu/miniconda2/bin/checkm, same when I type 'which checkm'. How do I set the pip-installed version as the one it should look to? (the above file path doesn't exist any more because the conda uninstall checkm-genome worked...)

One other Q - is there an ideal location to set the path to where all dependencies should already exist? This wasn;t clear from the installation instructions

**Comment by dparks1134** [comment]
You need to download the CheckM data files:
https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

I'm not sure about configuring conda. You can put the CheckM dependency data anywhere on your system that works for your setup.

**Comment by nixon444** [comment]
My bad - I hadn't downloaded the data files, what an idiot! :/ 

It's working now - thanks so much for helping me figure this, I really appreciate it and won't be making that mistake again!
